# Don't forget Permissions and ownership
# www-data should own wordpress plugins themes and uploads directories
# wordpress plugins and themes directories should be set to 775
# uploads directory should be set to 775

version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "${WP_PORT}:80"
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
      WORDPRESS_DEBUG: 1
      # Debugging
      # Here we are setting the debug constants to true
      # WP_DEBUG_LOG, if set to true, will log errors to wp-content/debug.log
      # WP_DEBUG_DISPLAY, if set to true, will display errors on the screen 
      # (not recommended for production because it can expose sensitive information)
      # SCRIPT_DEBUG, if set to true, will load the development (non-minified) versions of scripts
      # like css and js files
      # WP_ENVIRONMENT_TYPE, if set to local, allow to set application password for the REST API
      # We could also add SAVEQUERIES, if set to true, will save all the database queries to wp-content/debug.log
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ./wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads:rw # Read-Write Permission
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${WP_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wp-cli:
    image: wordpress:cli
    user: "33:33" # user
    # tty: true w
    tty: true
    volumes:
      - ./wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads:rw # Read-Write Permission
      - ./scripts:/scripts
      - ./backups:/backups
      - wp_cli_home:/home/www-data
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
      WP_DB_HOST: ${WP_DB_HOST}
      WP_PORT: ${WP_PORT}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    depends_on:
      - wordpress
      - db
    command: /scripts/wp-init.sh
volumes:
  db_data: {}
  wp_cli_home: {}
